name: Daily ETL

on:
  schedule:
    # زمان‌ها به وقت تهران
    # change time to start 3: 30 AM Tehran (ETL runs from Saturday to Wednesday, 
    # Also runs every 20 minutes from 3:10 AM to 6:10 AM Tehran)
    - cron: "30 0 * * 0-3,6"  # 3:30 Tehran -> UTC 00:30
    - cron: "50 0 * * 0-3,6"  # 3:50 Tehran -> UTC 00:50
    - cron: "10 1 * * 0-3,6"  # 4:10 Tehran -> UTC 01:10
    - cron: "30 1 * * 0-3,6"  # 4:30 Tehran -> UTC 01:30
    - cron: "50 1 * * 0-3,6"  # 4:50 Tehran -> UTC 01:50
    - cron: "10 2 * * 0-3,6"  # 5:10 Tehran -> UTC 02:10
    - cron: "30 2 * * 0-3,6"  # 5:30 Tehran -> UTC 02:30
    - cron: "50 2 * * 0-3,6"  # 5:50 Tehran -> UTC 02:50
    - cron: "10 3 * * 0-3,6"  # 6:10 Tehran -> UTC 03:10


  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
      BRSAPI_API_KEY: ${{ secrets.BRSAPI_API_KEY }}
      ETL_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test database connection
        run: python src/db.py

      - name: Run ETL
        run: python src/etl.py
