name: Daily ETL

on:
  schedule:
    # زمان‌ها به وقت تهران
    # change time to start 3: 30 AM Tehran (ETL runs from Saturday to Wednesday, 
    # Also runs every 20 minutes from 18:40 PM to 21:20 AM Tehran)
    - cron: "10 15 * * 0-3,6"  # 18:40 Tehran -> UTC 15:10
    - cron: "30 15 * * 0-3,6"  # 19:00 Tehran -> UTC 15:30
    - cron: "50 15 * * 0-3,6"  # 19:20 Tehran -> UTC 15:50
    - cron: "10 16 * * 0-3,6"  # 19:40 Tehran -> UTC 16:10
    - cron: "30 16 * * 0-3,6"  # 20:00 Tehran -> UTC 16:30
    - cron: "50 16 * * 0-3,6"  # 20:20 Tehran -> UTC 16:50
    - cron: "10 17 * * 0-3,6"  # 20:40 Tehran -> UTC 17:10
    - cron: "30 17 * * 0-3,6"  # 21:00 Tehran -> UTC 17:30
    - cron: "50 17 * * 0-3,6"  # 21:20 Tehran -> UTC 17:50


  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
      BRSAPI_API_KEY: ${{ secrets.BRSAPI_API_KEY }}
      ETL_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test database connection
        run: python src/db.py

      - name: Run ETL
        run: python src/etl.py
