name: Daily ETL

on:
  schedule:
    # زمان‌ها به وقت تهران
    # change time to start 19:30 PM Tehran (ETL runs from Saturday to Wednesday, 
    # Also runs every 20 minutes from 19:30 PM to 22:10 AM Tehran)
    - cron: "00 16 * * 0-3,6"  # 19:30 Tehran -> UTC 16:00
    - cron: "20 16 * * 0-3,6"  # 19:50 Tehran -> UTC 16:20
    - cron: "40 16 * * 0-3,6"  # 20:10 Tehran -> UTC 16:40
    - cron: "00 17 * * 0-3,6"  # 20:30 Tehran -> UTC 17:00
    - cron: "20 17 * * 0-3,6"  # 20:50 Tehran -> UTC 17:20
    - cron: "40 17 * * 0-3,6"  # 21:10 Tehran -> UTC 17:40
    - cron: "00 18 * * 0-3,6"  # 21:30 Tehran -> UTC 18:00
    - cron: "20 18 * * 0-3,6"  # 21:50 Tehran -> UTC 18:20
    - cron: "40 18 * * 0-3,6"  # 22:10 Tehran -> UTC 18:40


  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
      BRSAPI_API_KEY: ${{ secrets.BRSAPI_API_KEY }}
      ETL_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test database connection
        run: python src/db.py

      - name: Run ETL
        run: python src/etl.py
